### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toString')

### ISSUE THREAD

**Issue by angelamelinda** [Leanplum/Leanplum-JavaScript-SDK#144]
## Expected Behavior
No Errors 

## Actual Behavior
I got
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toString')`
It seems this error occurred in `ignoreCaseEquals` function in `Messages.ts`
<img width="594" alt="Screen Shot 2022-01-06 at 15 12 37" src="https://user-images.githubusercontent.com/19211116/148353236-cf8c0828-1964-42df-b251-879be0107702.png">

## Steps to Reproduce the Problem

  1. n/a

## Specifications

  - Version: 1.8.3
  - Platform: n/a
  - Subsystem: n/a

**Comment by gyoshev** [comment]
It appears that this may happen when an event is triggered with an "undefined" parameter, e.g. `Leanplum.track('Purchase', { item: undefined })`. Adding a patch with this assumption.

Providing steps to reproduce the problem would eliminate the guesswork.
