### ISSUE TITLE
SDK doesn't handle adblockers - retries failed requests forever

### ISSUE THREAD

**Issue by mogelbrod** [Leanplum/Leanplum-JavaScript-SDK#181]
Some Adblockers such as [uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm) unfortunately block requests to https://api.leanplum.com/api . The JS SDK doesn't handle this very well however, as it seems to retry the request every ~400ms forever. In addition to spamming the console it also seems to significantly slow down the web app.

## Expected Behavior
There are a number of possible solutions for this that can be applied, either one or many in tandem:
1. Implement exponential backoff for retries
2. Stop automatically retrying after a configurable time period
3. Stop retrying if the response object has `status = 0`

## Actual Behavior
The SDK retries the request every ~400ms forever.

## Steps to Reproduce the Problem

  1. Install a browser Adblock extension such as [uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm)
  1. Navigate to any website using the leanplum SDK
  1. Trigger a leanplum API request via `leanplum.forceContentUpdate()` or similar

## Specifications

  - Version: leanplum-sdk@1.11.0
  - Platform: Chrome 113.0.5672.126 (Official Build) (arm64)
  - Subsystem: ?

**Comment by gusost** [comment]
The issue is severely underreported to error tracking tools like Sentry since the same mechanisms that block connections to Leanplum also blocks connections to the error tracker.

**Comment by gyoshev** [comment]
I could not reproduce this on the [Rondo Web test application](https://leanplum.github.io/Leanplum-JavaScript-SDK/). Nevertheless, server responses with `status=0` suppress further traffic in version `1.11.1`. If this doesn't fix the issue for you, please provide a sample page that demonstrates the issue.

**Comment by mogelbrod** [comment]
Thanks! Would it be possible to release the fix for v1.10.x as well? #183 is preventing us from upgrading.
