### ISSUE TITLE
Types are missing in the node module

### ISSUE THREAD

**Issue by derrickpelletier** [Leanplum/Leanplum-JavaScript-SDK#182]
## Expected Behavior

Expecting `dist/leanplum.d.ts` to exist, as it is referenced in `package.json` as location for type defs, and it is also in the git repo dist folder.

## Actual Behavior

`dist/leanplum.d.ts` doesn't exist in the installed npm module.

## Steps to Reproduce the Problem

  1. Install `leanplum-sdk@1.11.0`
  1. View installed module and see there are no types in dist folder
  1. Importing module into project lacks type defs.

## Specifications

  - Version: 1.11.0
  - Platform: node.js
  - Subsystem: os x

**Comment by derrickpelletier** [comment]
The types were present in `1.10.5`

**Comment by gyoshev** [comment]
Fixed in `1.11.1`.
