### ISSUE TITLE
Bundled size increased from 68kb (v1.10.5) to 194kb (v1.11.0)

### ISSUE THREAD

**Issue by mogelbrod** [Leanplum/Leanplum-JavaScript-SDK#183]
Upgrading leanplum-sdk from v1.10.5 to v.1.11.0 results in a huge increase in bundle size.

## Expected Behavior
Bundle size should barely change - or preferably decrease.

## Actual Behavior
Bundle size of the package greatly increased, from **68kb** (v1.10.5) to **194kb** (v1.11.0).

## Steps to Reproduce the Problem

  1. Clone/create a new project using webpack to bundle assets
  2. Import leanplum-sdk into a JS chunk
  3. Configure https://www.npmjs.com/package/webpack-bundle-analyzer to run when bundling
  4. `npm install leanplum-sdk@1.10.x`
  1. Run webpack and note the size of the leanplum-sdk chunk
  1. `npm install leanplum-sdk@1.11.0`
  2. Run webpack and note the size of the leanplum-sdk chunk

## Specifications

  - Version: v1.11.0
  - Platform: Mac
  - Subsystem: N/A

**Comment by gyoshev** [comment]
@mogelbrod version `1.11.0` bundles the CleverTap JS SDK as a dependency, in order to allow for easy migration to it. You can continue using version `1.10.5` until you decide to migrate, and start using the CleverTap SDK directly afterwards.
