### ISSUE TITLE
Updating to 1.3.0 - Problem declaring default variables

### ISSUE THREAD

**Issue by nicolasyousician** [Leanplum/Leanplum-JavaScript-SDK#22]
## Expected Behavior
No errors should be shown and/or there shouldn't be need to define all the existing variables

## Actual Behavior
Leanplum throws the following error 
```
Uncaught TypeError: Cannot read property 'Daily Activity Goal' of undefined
```
For every single group not defined when doing `Leanplum.setVariables({...})`. It seems that every single group needs to be defined otherwise this will fail. On previous versions this wasn't an issue.

## Steps to Reproduce the Problem

  1. n/a

## Specifications

  - Version: n/a
  - Platform: n/a
  - Subsystem: n/a

**Comment by gyoshev** [comment]
The fix is released in `1.5.0` of the SDK.
