### ISSUE TITLE
Creating an in-app messaging template with the JavaScript SDK

### ISSUE THREAD

**Issue by skoshy** [Leanplum/Leanplum-JavaScript-SDK#55]
## Expected Behavior
Want to be able to send in-app messages using the JS SDK, or define custom in-app messages using the JS SDK

## Actual Behavior
Triggering in-app messages doesn't propagate to JS SDK dev clients, nor can I find a method to register in-app messaging templates in the JS SDK

## Specifications

  - Version: 1.4.0
  - Platform: macOS, but using the latest JS SDK

**Comment by gyoshev** [comment]
Hello @skoshy, 

This feature is underway, started with https://github.com/Leanplum/Leanplum-JavaScript-SDK/pull/98. For the initial release, we don't plan on providing the ability to add custom templates from the JS SDK. You'll be able to process the JSON of messages that have been configured through the Dashboard. Would that suffice for your use-case?

**Comment by skoshy** [comment]
I believe this should be sufficient; if I'm understanding correctly we could parse the JSON and determine the type of in-app message and display our own custom popover or something similar

**Comment by gyoshev** [comment]
[Version `1.7.0`](https://github.com/Leanplum/Leanplum-JavaScript-SDK/releases/tag/1.7.0) of the SDK has been released -- you can verify if it fits your use-case. Sample code that integrates messages in a Bootstrap site can be found [in the e2e test application](https://github.com/Leanplum/Leanplum-JavaScript-SDK/blob/develop/test/e2e/index.ts#L278-L284) ([hosted here](https://leanplum.github.io/Leanplum-JavaScript-SDK/)). Sample JSON for the default messages is [listed in the documentation](https://docs.leanplum.com/reference#web-in-app-messages), along with current limitations. Make sure to communicate the latter with the person who is running the campaigns.

This should be enough to unblock messaging scenarios. We're thinking of ways to improve the developer experience and lift some of the limitations in future releases. Let me know what you think.
